server:
  port: 8080

spring:
  datasource:
    username: root
    password: upic1234
    url: jdbc:mysql://115.159.193.237:3306/xlzb?characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true